// <auto-generated />
using System;
using BillingExtractor.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BillingExtractor.Data.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20260131120535_AddInvoiceAdjustments")]
    partial class AddInvoiceAdjustments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BillingExtractor.Data.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("IssuedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("VendorName");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("BillingExtractor.Data.Entities.Invoice", b =>
                {
                    b.OwnsMany("BillingExtractor.Data.Entities.InvoiceAdjustment", "Adjustments", b1 =>
                        {
                            b1.Property<int>("InvoiceId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<decimal>("Amount");

                            b1.Property<string>("Description");

                            b1.HasKey("InvoiceId", "__synthesizedOrdinal");

                            b1.ToTable("Invoices");

                            b1
                                .ToJson("Adjustments")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceId");
                        });

                    b.OwnsMany("BillingExtractor.Data.Entities.InvoiceItem", "Items", b1 =>
                        {
                            b1.Property<int>("InvoiceId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<decimal>("Amount");

                            b1.Property<string>("Description");

                            b1.Property<string>("ItemId")
                                .IsRequired();

                            b1.Property<decimal>("Quantity");

                            b1.Property<string>("Unit")
                                .IsRequired();

                            b1.Property<decimal>("UnitPrice");

                            b1.HasKey("InvoiceId", "__synthesizedOrdinal");

                            b1.ToTable("Invoices");

                            b1
                                .ToJson("Items")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceId");
                        });

                    b.Navigation("Adjustments");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
